---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: redis
        imagePullPolicy: Never
        ports:
          - containerPort: 5001
        env:
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_HOST
          value: redis
          - name: root_user
            valueFrom:
              secretKeyRef:
                name: secrets
                key: root_user
          - name: root_password
            valueFrom:
              secretKeyRef:
                name: secrets
                key: root_password